import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{BookOpen,CalendarDays,Check,Dumbbell,Heart,Leaf,LogOut,NotebookPen,Palette,Plus,RotateCcw,Ruler,Sparkles,Trash2,X}from"lucide-react";
import{supabase}from"./supabase";
import"./style.css";

const habitSeed=[["Ler","book","Todos os dias"],["Meditação 10 min","sparkles","Todos os dias"],["Exercício","gym","4× por semana"],["Momento com Deus","heart","Todos os dias"],["Arte","art","Quando precisar"],["Beber chá verde","leaf","Todos os dias"],["Journal","journal","Todos os dias"]];
const taskSeed=[["Revisão de Literatura","2026-03-01","2027-07-31"],["Estabelecimento de parcerias e desenvolvimento do protocolo de avaliação","2026-05-01","2026-09-30"],["Submissão à comissão de ética","2026-09-01","2026-09-30"],["Recrutamento e recolha de dados","2026-10-01","2027-01-31"],["Análise de dados","2027-02-01","2027-03-31"],["Interpretação e discussão","2027-04-01","2027-05-31"],["Entrega da dissertação","2027-06-01","2027-06-30"],["Defesa da dissertação","2027-07-01","2027-07-31"]];
const artIdeas=["Pintar com aguarela","Fazer um desenho livre","Colagem criativa","Pintar por números","Modelar barro","Fotografia criativa","Desenhar flores","Experimentar lettering"];
const iconMap={book:<BookOpen/>,sparkles:<Sparkles/>,gym:<Dumbbell/>,heart:<Heart/>,art:<Palette/>,leaf:<Leaf/>,journal:<NotebookPen/>};
const now=()=>new Date().toISOString().slice(0,10);
const fmt=d=>new Date(d+"T12:00:00").toLocaleDateString("pt-PT",{month:"short",year:"numeric"});

function App(){
 const[session,setSession]=useState(null),[ready,setReady]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(r=>{setSession(r.data.session);setReady(true)});const s=supabase.auth.onAuthStateChange((_e,x)=>setSession(x));return()=>s.data.subscription.unsubscribe()},[]);
 if(!ready)return <div className="splash"><Logo/><p>a preparar o teu espaço…</p></div>;
 return session?<Dashboard session={session}/>:<Auth/>;
}
function Auth(){
 const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[signup,setSignup]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function submit(e){e.preventDefault();setBusy(true);setMessage("");const r=signup?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});setBusy(false);setMessage(r.error?r.error.message:signup?"Conta criada. Confirma o email e depois inicia sessão.":"")}
 return <main className="auth"><section><div className="authart"><Logo/><p>Small steps, soft days,<br/><i>beautiful progress.</i></p></div><form onSubmit={submit}><em>O teu espaço pessoal</em><h1>{signup?"Cria o teu espaço ♡":"Bem-vinda de volta ♡"}</h1><p>Hábitos, tese e evolução — tudo num lugar só.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Palavra-passe<input type="password" minLength="6" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<div className="message">{message}</div>}<button className="primary">{busy?"A guardar…":signup?"Criar conta":"Entrar"}</button><button type="button" className="link" onClick={()=>{setSignup(!signup);setMessage("")}}>{signup?"Já tens conta? Entrar":"Ainda não tens conta? Criar conta"}</button></form></section></main>;
}
function Dashboard({session}){
 const[tab,setTab]=useState("daily"),[habits,setHabits]=useState([]),[tasks,setTasks]=useState([]),[measures,setMeasures]=useState([]),[done,setDone]=useState(new Set()),[modal,setModal]=useState(null),[art,setArt]=useState(artIdeas[0]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);const q=await Promise.all([supabase.from("habits").select("*").order("sort_order"),supabase.from("thesis_tasks").select("*").order("sort_order"),supabase.from("measurements").select("*").order("measured_month"),supabase.from("habit_completions").select("habit_id").eq("completed_on",now())]);const bad=q.find(x=>x.error);if(bad){setError("Executa o ficheiro supabase/schema.sql no SQL Editor do Supabase.");setLoading(false);return}if(!q[0].data.length){await supabase.from("habits").insert(habitSeed.map((x,i)=>({name:x[0],icon:x[1],frequency:x[2],sort_order:i+1})));return load()}if(!q[1].data.length){await supabase.from("thesis_tasks").insert(taskSeed.map((x,i)=>({title:x[0],start_date:x[1],end_date:x[2],sort_order:i+1})));return load()}setHabits(q[0].data);setTasks(q[1].data);setMeasures(q[2].data);setDone(new Set(q[3].data.map(x=>x.habit_id)));setLoading(false)}
 useEffect(()=>{load()},[]);
 async function toggleHabit(id){done.has(id)?await supabase.from("habit_completions").delete().eq("habit_id",id).eq("completed_on",now()):await supabase.from("habit_completions").insert({habit_id:id,completed_on:now()});const n=new Set(done);n.has(id)?n.delete(id):n.add(id);setDone(n)}
 async function toggleTask(t){await supabase.from("thesis_tasks").update({is_done:!t.is_done}).eq("id",t.id);setTasks(v=>v.map(x=>x.id===t.id?{...x,is_done:!x.is_done}:x))}
 async function remove(table,id,setter){if(!confirm("Queres mesmo eliminar?"))return;await supabase.from(table).delete().eq("id",id);setter(v=>v.filter(x=>x.id!==id))}
 const hp=Math.round(done.size/Math.max(habits.length,1)*100),tp=Math.round(tasks.filter(x=>x.is_done).length/Math.max(tasks.length,1)*100),latest=measures.at(-1),previous=measures.at(-2),diff=latest&&previous?Number(latest.weight)-Number(previous.weight):null;
 return <div className="shell"><aside><Logo/><nav><Nav active={tab==="daily"} go={()=>setTab("daily")} icon={<CalendarDays/>}>Daily list</Nav><Nav active={tab==="thesis"} go={()=>setTab("thesis")} icon={<BookOpen/>}>Tese</Nav><Nav active={tab==="gym"} go={()=>setTab("gym")} icon={<Dumbbell/>}>Gym girlie</Nav></nav><div className="quote"><Sparkles/><p>Small steps, soft days,<br/><i>beautiful progress.</i></p></div><div className="profile"><b>♡</b><span>{session.user.email}<button onClick={()=>supabase.auth.signOut()}><LogOut/>Sair</button></span></div></aside><main><div className="mobiletop"><Logo/></div><div className="mobilenav"><Nav active={tab==="daily"} go={()=>setTab("daily")} icon={<CalendarDays/>}>Daily</Nav><Nav active={tab==="thesis"} go={()=>setTab("thesis")} icon={<BookOpen/>}>Tese</Nav><Nav active={tab==="gym"} go={()=>setTab("gym")} icon={<Dumbbell/>}>Gym</Nav></div>{error?<div className="error"><h2>Falta ativar a base de dados</h2><p>{error}</p></div>:loading?<div className="splash">a carregar…</div>:tab==="daily"?<Daily data={habits} done={done} progress={hp} toggle={toggleHabit} remove={id=>remove("habits",id,setHabits)} art={art} roll={()=>setArt(artIdeas[Math.floor(Math.random()*artIdeas.length)])} add={()=>setModal("habit")}/>:tab==="thesis"?<Thesis data={tasks} progress={tp} toggle={toggleTask} remove={id=>remove("thesis_tasks",id,setTasks)} add={()=>setModal("task")}/>:<Gym data={measures} latest={latest} diff={diff} remove={id=>remove("measurements",id,setMeasures)} add={()=>setModal("measure")}/>}</main>{modal&&<Modal type={modal} close={()=>setModal(null)} saved={load}/>}</div>;
}
function Daily({data,done,progress,toggle,remove,art,roll,add}){return <div className="page"><Title eyebrow={new Date().toLocaleDateString("pt-PT",{weekday:"long",day:"numeric",month:"long"})} title="Bom dia, bonita" sub="Hoje não precisas de fazer tudo. Só precisas de começar." action={add} button="Novo hábito"/><div className="dailygrid"><section className="card panel"><CardTitle label="O teu ritmo" title="Daily list"><div className="ring" style={{"--p":progress*3.6+"deg"}}><span>{progress}%</span></div></CardTitle>{data.map(h=><div className={"row "+(done.has(h.id)?"done":"")} key={h.id}><button className="check" onClick={()=>toggle(h.id)}>{done.has(h.id)&&<Check/>}</button><i>{iconMap[h.icon]||<Sparkles/>}</i><div><b>{h.name}</b><small>{h.frequency}</small></div><Delete go={()=>remove(h.id)}/></div>)}<button className="add" onClick={add}><Plus/>Adicionar à lista</button></section><div className="side"><section className="card art"><div className="arthead"><i><Palette/></i><div><em>Momento criativo</em><h2>Roleta da arte</h2></div></div><p>Deixa o acaso escolher e começa sem pensar demasiado.</p><div className="result"><small>Hoje vais…</small><b>{art}</b></div><button className="primary" onClick={roll}><RotateCcw/>Rodar a roleta</button></section><section className="card reminder"><Sparkles/><div><em>Lembrete do dia</em><p>“A disciplina também pode ser uma forma de carinho por ti.”</p></div></section></div></div></div>}
function Thesis({data,progress,toggle,remove,add}){return <div className="page"><Title eyebrow="a tua investigação" title="A minha tese" sub="Um passo de cada vez até à defesa." action={add} button="Adicionar tarefa"/><div className="stats"><Stat l="Progresso geral" v={progress+"%"} n={data.filter(x=>x.is_done).length+" de "+data.length+" fases concluídas"}/><Stat l="Próximo marco" v="Set 2026" n="Submissão à comissão de ética"/><Stat l="Objetivo final" v="Jul 2027" n="Defesa da dissertação"/></div><section className="card panel"><CardTitle label="Planificação" title="Checklist da tese"><span className="pill"><CalendarDays/>Mar 2026 — Jul 2027</span></CardTitle>{data.map((t,i)=><div className={"task "+(t.is_done?"done":"")} key={t.id}><button className="check" onClick={()=>toggle(t)}>{t.is_done&&<Check/>}</button><i>{String(i+1).padStart(2,"0")}</i><div><b>{t.title}</b><small><CalendarDays/>{fmt(t.start_date)} — {fmt(t.end_date)}</small></div><Delete go={()=>remove(t.id)}/></div>)}</section></div>}
function Gym({data,latest,diff,remove,add}){return <div className="page"><Title eyebrow="strong body · soft heart" title="Gym girlie" sub="Regista a tua evolução sem pressa e sem pressão." action={add} button="Novo registo"/><div className="stats"><Stat l="Peso atual" v={latest?latest.weight+" kg":"— kg"} n={diff==null?"Adiciona o primeiro registo":(diff>0?"+":"")+diff.toFixed(1)+" kg desde o mês anterior"}/><Stat l="Último registo" v={latest?fmt(latest.measured_month):"—"} n="Registo mensal"/><Stat l="Registos" v={String(data.length)} n="A tua jornada até agora"/></div>{!data.length?<section className="card empty"><i><Ruler/></i><h2>Começa a tua jornada</h2><p>Regista o peso e as medidas uma vez por mês.</p><button className="primary" onClick={add}><Plus/>Adicionar primeiro registo</button></section>:<section className="card panel"><CardTitle label="Histórico" title="Medidas mensais"><button className="round" onClick={add}><Plus/></button></CardTitle><div className="tablewrap"><table><thead><tr><th>Mês</th><th>Peso</th><th>Cintura</th><th>Anca</th><th>Peito</th><th>Coxa</th><th>Braço</th><th/></tr></thead><tbody>{[...data].reverse().map(m=><tr key={m.id}><td>{fmt(m.measured_month)}</td><td>{m.weight} kg</td>{[m.waist,m.hip,m.chest,m.thigh,m.arm].map((x,i)=><td key={i}>{x||"—"} cm</td>)}<td><Delete go={()=>remove(m.id)}/></td></tr>)}</tbody></table></div></section>}</div>}
function Logo(){return <div className="logo"><i>h</i><div><b>her space</b><small>the soft life planner</small></div></div>}function Nav({active,go,icon,children}){return <button className={active?"active":""} onClick={go}>{icon}{children}</button>}function Title({eyebrow,title,sub,action,button}){return <header className="title"><div><em>{eyebrow}</em><h1>{title}<i>♡</i></h1><p>{sub}</p></div><button onClick={action}><Plus/>{button}</button></header>}function CardTitle({label,title,children}){return <div className="cardtitle"><div><em>{label}</em><h2>{title}</h2></div>{children}</div>}function Delete({go}){return <button className="delete" onClick={go}><Trash2/></button>}function Stat({l,v,n}){return <section className="card stat"><em>{l}</em><b>{v}</b><small>{n}</small></section>}
function Modal({type,close,saved}){async function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);let q;if(type==="habit")q=supabase.from("habits").insert({name:f.get("name"),icon:f.get("icon"),frequency:f.get("frequency")});if(type==="task")q=supabase.from("thesis_tasks").insert({title:f.get("title"),start_date:f.get("start"),end_date:f.get("end")});if(type==="measure")q=supabase.from("measurements").upsert({measured_month:f.get("date")+"-01",weight:f.get("weight"),waist:f.get("waist")||null,hip:f.get("hip")||null,chest:f.get("chest")||null,thigh:f.get("thigh")||null,arm:f.get("arm")||null},{onConflict:"user_id,measured_month"});const r=await q;if(r.error)alert(r.error.message);else{close();saved()}}return <div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="modal"><button className="close" onClick={close}><X/></button><em>Personalizar</em><h2>{type==="habit"?"Novo hábito":type==="task"?"Nova tarefa da tese":"Novo registo mensal"}</h2><form onSubmit={submit}>{type==="habit"&&<><label>Nome<input name="name" required/></label><div className="fields"><label>Ícone<select name="icon"><option value="book">Livro</option><option value="sparkles">Brilho</option><option value="gym">Exercício</option><option value="heart">Coração</option><option value="art">Arte</option><option value="leaf">Folha</option><option value="journal">Journal</option></select></label><label>Frequência<input name="frequency" defaultValue="Todos os dias"/></label></div></>}{type==="task"&&<><label>Tarefa<textarea name="title" required/></label><div className="fields"><label>Início<input type="date" name="start" required/></label><label>Fim<input type="date" name="end" required/></label></div></>}{type==="measure"&&<><div className="fields"><label>Mês<input type="month" name="date" required/></label><label>Peso (kg)<input type="number" step=".1" name="weight" required/></label></div><div className="fields three">{[["waist","Cintura"],["hip","Anca"],["chest","Peito"],["thigh","Coxa"],["arm","Braço"]].map(x=><label key={x[0]}>{x[1]} (cm)<input name={x[0]} type="number" step=".1"/></label>)}</div></>}<div className="actions"><button type="button" onClick={close}>Cancelar</button><button className="primary">Guardar</button></div></form></section></div>}
createRoot(document.getElementById("root")).render(<App/>);
